# Generated by Django 4.0.3 on 2022-06-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_department_dept_date_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Books.department'),
        ),
    ]
